# Generated by Django 4.1.5 on 2023-01-16 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker',
            name='IsSubscribed',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='experiance',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='github',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='phone_number',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='protofolio',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='usermedia',
            name='CV',
            field=models.FileField(null=True, upload_to='media/%y'),
        ),
        migrations.AlterField(
            model_name='usermedia',
            name='image',
            field=models.FileField(null=True, upload_to='media/%y'),
        ),
        migrations.AlterField(
            model_name='usermedia',
            name='video',
            field=models.FileField(null=True, upload_to='media/%y'),
        ),
    ]
