# Generated by Django 4.1.5 on 2023-01-16 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_jobseeker_issubscribed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdetails',
            name='city',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='country',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='jobTitle',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='clientdetails',
            name='education',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='about_company',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_address',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_website',
            field=models.URLField(max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.FileField(null=True, upload_to='media/%y'),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='ShortList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.company')),
                ('jobseeker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.jobseeker')),
            ],
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('notes', models.TextField()),
                ('isApproved_jobseeker', models.BooleanField(null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.company')),
                ('jobseeker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.jobseeker')),
            ],
        ),
    ]
