# Generated by Django 4.0 on 2023-01-20 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('phoneNumber', models.CharField(max_length=200, null=True)),
                ('owner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute', models.CharField(max_length=200, null=True)),
                ('degree', models.CharField(max_length=200, null=True)),
                ('major', models.CharField(max_length=200, null=True)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('owner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=200, null=True)),
                ('country', models.CharField(max_length=200, null=True)),
                ('lastName', models.CharField(max_length=200, null=True)),
                ('jobtitle', models.CharField(max_length=200, null=True)),
                ('yearsExperience', models.CharField(max_length=200, null=True)),
                ('age', models.CharField(max_length=200, null=True)),
                ('owner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperiance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('subTitle', models.CharField(max_length=200, null=True)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('description', models.TextField(null=True)),
                ('owner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.customuser')),
            ],
        ),
        migrations.RenameField(
            model_name='clientdetails',
            old_name='skilles',
            new_name='skills',
        ),
        migrations.RemoveField(
            model_name='clientdetails',
            name='city',
        ),
        migrations.RemoveField(
            model_name='clientdetails',
            name='country',
        ),
        migrations.RemoveField(
            model_name='clientdetails',
            name='education',
        ),
        migrations.RemoveField(
            model_name='clientdetails',
            name='jobTitle',
        ),
        migrations.RemoveField(
            model_name='usermedia',
            name='CV',
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='github',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='linkedin',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='porto',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='summary',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='interview',
            name='jobseeker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.customuser'),
        ),
        migrations.AlterField(
            model_name='recentlyviewd',
            name='jobseeker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.customuser'),
        ),
        migrations.AlterField(
            model_name='shortlist',
            name='jobseeker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.customuser'),
        ),
        migrations.DeleteModel(
            name='JobSeeker',
        ),
    ]
