# Generated by Django 4.0 on 2023-01-20 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_contact_education_personalinfo_workexperiance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='end',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='start',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='workexperiance',
            name='end',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='workexperiance',
            name='start',
            field=models.DateField(null=True),
        ),
    ]
